version: '3'
services:
  git:
    image: chrisrao/git-test-server
    volumes:
    - ./all_users:/git-test-server-users/users
    - keys:/git-test-server-keys
  test:
    build:
      context: .
    volumes:
    - keys:/keys
    - ./assistant:/content/assistant
    - ./scripts:/content/scripts
    depends_on:
    - "git"
volumes:
  keys:
