FROM alpine

RUN apk update && apk add --update openssh-client

VOLUME /keygen

COPY ["all_users", "/"]
COPY ["generate_all_user_keys.sh", "/"]

RUN mkdir /keys
RUN chmod +x /generate_all_user_keys.sh
RUN /generate_all_user_keys.sh

CMD cp /keys/* /keygen