FROM winlu/docker-git-server

VOLUME /keygen

COPY ["all_users", "/"]
COPY ["add_all_users.sh", "/"]
COPY ["delete_all_users.sh", "/"]
COPY ["git_bootstrap.sh", "/git"]

RUN chmod +x /add_all_users.sh
RUN chmod +x /delete_all_users.sh
RUN chmod +x /git/git_bootstrap.sh

ENTRYPOINT ["/git/git_bootstrap.sh"]