version: '3'
services:
  git:
    build:
      context: .
      dockerfile: Dockerfile.git
    ports:
      - "2222:22"
    volumes:
    - keygen:/keygen
    depends_on:
    - "keygen"
  keygen:
    build:
      context: .
      dockerfile: Dockerfile.keygen
    volumes:
    - keygen:/keygen
  test:
    build:
      context: .
    volumes:
    - keygen:/keygen
    - ./assistant:/content/assistant
    - ./scripts:/content/scripts
    depends_on:
    - "keygen"
    - "git"
volumes:
  keygen:
  keys:
  repos:
